### ISSUE TITLE
[BUG] 'deposit' method in Pot endpoint checks for funds in wrong source

### ISSUE THREAD

**Issue by eliasbenaddou** [petermcd/monzo-api#55]
**Describe the bug**
I'm using the Pot endpoint to move funds from my main account to one of my pots and the error about insufficient funds is always raised. I am trying to deposit money from my main account which has sufficient funds, into a pot, so it should not be checking the pot balance at the beginning of the deposit method. This checking seems to only be needed for withdrawing from pots.

**Expected behavior**
For money to be deposited into a pot from the account id (main account)
**Environment (please complete the following information):**
 - 0.2.0
 - 3.8.10

**Comment by petermcd** [comment]
Thanks @eliasbenaddou will take a look, likely be over the weekend to be honest atm.

**Comment by eliasbenaddou** [comment]
No problem! Amazing package btw, I’ve been using it for quite a while and wanted to reach out for sometime. I may submit a PR if that helps?

**Comment by petermcd** [comment]
Thankyou, glad you like the package, 

Regarding a PR by all means always welcome a PR if you can,

**Comment by petermcd** [comment]
Thanks again @eliasbenaddou thats it merged in, will release momentarily
