### ISSUE TITLE
[BUG] Fetching balance always returns cached value. (2) There's no way currently to invalidate the cache

### ISSUE THREAD

**Issue by dcaspi** [petermcd/monzo-api#58]
**Describe the bug**
Once the balance has been fetched once, it's stored as is in Account.
 If the balance has changed (say because the user has purchased something), there's currently no way to fetch the new balance without fetching all accounts all over again.

**To Reproduce**
1. Fetch Accounts objects
2. Print the balance in your main one
3. Get yourself a coffee
4. Fetch the balance again

**Expected behavior**
The new balance will be shown or there will be a way to force fetching the new balance.
Probably best to have a way to force fetching the new balance, as caching could be useful.

**Comment by petermcd** [comment]
Hi @dcaspi

Sounds like an obvious feature to add. I personally use it for in the moment checks so would fetch everything again anyway but this should be easy to implement.

Will likely be at the weekend before I can take a look.

**Comment by petermcd** [comment]
This can now be carried out by calling the fetch_balance() method of account. Calling the balance property will continue to fetch the already fetched balance if one exists.

If you are simply dealing with a balance object then a simple call to Balance.fetch() will generate a new balance object.
